export const REGISTRO_EXITOSO = "REGISTRO_EXITOSO";
export const REGISTRO_ERROR = "REGISTRO_ERROR";
export const OBTENER_USUARIO = "OBTENER_USUARIO";
export const LOGIN_EXITOSO = "LOGIN_EXITOSO";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const CERRAR_SESION = "CERRAR_SESION";

export const CREAR_TABATTA = "CREAR_TABATTA";
export const CREAR_TABATTA_ERROR = "CREAR_TABATTA_ERROR";
export const CREAR_TABATTA_EXITO = "CREAR_TABATTA_EXITO";

export const OBTENER_TABATTA = "OBTENER_TABATTA";
export const OBTENER_TABATTA_ERROR = "OBTENER_TABATTA_ERROR";
export const OBTENER_TABATTA_EXITO = "OBTENER_TABATTA_EXITO";

export const AGREGAR_EJERCICIO = "AGREGAR_EJERCICIO";
export const AGREGAR_EJERCICIO_ERROR = "AGREGAR_EJERCICIO_ERROR";
export const AGREGAR_EJERCICIO_EXITO = "AGREGAR_EJERCICIO_EXITO";

export const OBTENER_EJERCICIOS_TABATTA = "OBTENER_EJERCICIOS_TABATTA";
export const OBTENER_EJERCICIOS_TABATTA_ERROR = "OBTENER_EJERCICIOS_TABATTA_ERROR";
export const OBTENER_EJERCICIOS_TABATTA_EXITO = "OBTENER_EJERCICIOS_TABATTA_EXITO";